---
- hosts: dev-syslog
  become: yes
  tasks:
  - name: Wait for port 22 to become open 
    wait_for:
      port: 22
      search_regex: OpenSSH
  - name: Add a user for dan
    user:
      name: dan
      comment: Dan Kelly
      groups: wheel
  - name: Set authorized key taken from file
    authorized_key:
      user: dan
      state: present
      key: "{{ lookup('file', '~/iac/keys/dan.pub') }}"
