---
- name: Import {{ item.path }}
  shell: "mysql < {{ item.path }}"
- name: Copy {{ item.path }} to processed directory
  copy: 
    remote_src: true 
    src: "{{ item.path }}"
    dest: /root/schemas/processed
- name: Remove {{ item.path }}
  file:
    path: "{{ item.path }}"
    state: absent