---
- hosts: localhost
  tasks:
  - name: Remove dev-bastion from known hostsa
    known_hosts:
      name: dev-bastion
      state: absent
- hosts: dev-bastion
  become: yes
  tasks:
  - name: Wait for port 22 to become open 
    wait_for:
      port: 22
      search_regex: OpenSSH
  - name: Add a user for dan
    user:
      name: dan
      password: $6$xlasbP1b55VK5M.5$jGaAwBxYFjLpc7kwREwYYjzagtWLrSPkhqGEJ2nQpMdDX62DzbLpiRDSXVf0ukKnTQMxMmPa68L2sBqX8XMdr0
      comment: Dan Kelly
      groups: wheel
  - name: Set authorized key taken from file
    authorized_key:
      user: dan
      state: present
      key: "{{ lookup('file', '~/iac/keys/dan.pub') }}"
