---
- hosts: "{{ env | default('dev')}}-bastion"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
    users:
     - dan
  tasks:
    - include_tasks: "../users/playbook-admin.yaml"
      loop: "{{ users }}"
      loop_control:
        loop_var: user