---
- hosts: dev-bastion
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
  - name: Add a user for dan with example password
    user:
      name: dan
      password: $6$xlasbP1b55VK5M.5$jGaAwBxYFjLpc7kwREwYYjzagtWLrSPkhqGEJ2nQpMdDX62DzbLpiRDSXVf0ukKnTQMxMmPa68L2sBqX8XMdr0
      comment: Dan Kelly
      groups: wheel
  - name: Set authorized key for dan
    authorized_key:
      user: dan
      state: present
      key: "{{ lookup('file', iac_home + '/keys/dan.pub') }}"