- hosts: localhost
  tasks:
  - name: Remove dev-bastion from known hosts
    known_hosts:
      name: dev-bastion
      state: absent
  - name: Remove dev-syslog from known hosts
    known_hosts:
      name: dev-syslog
      state: absent
  - name: Remove dev-docker from known hosts
    known_hosts:
      name: dev-docker
      state: absent
  - name: Remove docker by host name
    known_hosts:
      name: docker.dev.internal
      state: absent
  - name: Remove docker by host name
    known_hosts:
      name: syslog.dev.internal
      state: absent
  - name: Remove bastion IP from known hosts
    known_hosts:
      name: 10.0.1.10
      state: absent
  - name: Remove syslog IP from known hosts
    known_hosts:
      name: 10.0.1.20
      state: absent
  - name: Remove docker IP from known hosts
    known_hosts:
      name: 10.0.1.40
      state: absent
