- hosts: localhost
  tasks:
  - name: Remove bastion by SSH alias
    known_hosts:
      name: "{{ env }}-bastion"
      state: absent
  - name: Remove bastion by host name
    known_hosts:
      name: "bastion.{{ env }}.internal"
      state: absent
  - name: Remove syslog by SSH alias
    known_hosts:
      name: "{{ env }}-syslog"
      state: absent
  - name: Remove syslog by host name
    known_hosts:
      name: "syslog.{{ env }}.internal"
      state: absent
  - name: Remove docker by SSH alias
    known_hosts:
      name: "{{ env }}-docker"
      state: absent
  - name: Remove docker by host name
    known_hosts:
      name: "docker.{{ env }}.internal"
      state: absent