---
- hosts: "{{ env | default('dev')}}-docker"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
  - name: Copy daemon.json to /etc/docker
    copy:
      src: '{{ iac_home }}/ansible/docker/conf/docker/daemon.json'
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'
    tags:
    - conf
  - name: Add docker.conf to /etc/rsyslog.d using docker.conf.js template
    template:
      src: '{{ iac_home }}/ansible/docker/conf/rsyslog.d/docker.conf.j2'
      dest: /etc/rsyslog.d/docker.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy docker to /etc/logrotate.d
    copy:
      src: '{{ iac_home }}/ansible/docker/conf/logrotate/docker'
      dest: /etc/logrotate.d
      owner: root
      group: root
      mode: '0644'
  - name: Restart syslog service
    service:
      name: rsyslog
      state: restarted
  - name: Restart docker
    service:
      name: docker
      state: restarted
  - name: create a symlink for logrotate in cron.hourly
    file:
      src: /etc/cron.daily/logrotate
      dest: /etc/cron.hourly/logrotate
      state: link
