---
- hosts: "{{ env | default('dev')}}-docker"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
  tasks:
  - name: Copy rsyslog-client.conf to /etc/rsyslog.conf
    copy:
      src: '{{ iac_home }}/ansible/syslog/conf/rsyslog/rsyslog-client.conf'
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: '0644'
  - name: Restart syslog service
    service:
      name: rsyslog
      state: restarted
