---
- hosts: "{{ env | default('dev')}}-docker"
  become: yes
  vars:
    iac_home: "{{ lookup('env', 'IAC_HOME') }}"
    users:
     - dan
  tasks:
  - name: Install docker
    yum:
      name: docker
      state: present
  - name: Start service docker, if not started, make sure it is always enabled
    service:
      name: docker
      state: started
      enabled: yes
  - include_tasks: "../users/playbook-admin.yaml"
    loop: "{{ users }}"
    loop_control:
      loop_var: user
  - include_tasks: "../users/playbook-docker.yaml"
    loop: "{{ users }}"
    loop_control:
      loop_var: user