---
- name: Add user "{{ user }}"
  user:
    name: "{{ user }}"
- name: Set authorized key
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', iac_home + '/keys/{{ user }}.pub') }}"
