- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create SSH tunnel
    shell: ssh -fN -L 13306:mysql.dev.internal:3306 dev-bastion

  - name: Create database user 'dan' with all privileges
    ignore_errors: yes
    mysql_user:
      login_host: 127.0.0.1
      login_port: 13306
      name: dan
      password: top-s3cr3t!
      priv: '*.*:ALL'
      state: present

  - name: Get running SSH pid
    ignore_errors: yes
    shell: "ps aux | grep 13306 | grep ssh | awk '{print $2}'"
    register: running_processes

  - name: Kill running processes
    ignore_errors: yes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
     
  - name: Force kill stuck processes
    ignore_errors: yes
    shell: "kill -9 {{ item }}"
    with_items: "{{ processes.results | select('failed') | map(attribute='item') | list }}"
